#Dachcom:
#  OpenID:
#    users:
#      -
#        alias: admin
#        identity: http://admin.openid-provider.com/

TYPO3:
  Flow:
    security:
      authentication:
        authenticationStrategy: oneToken
        providers:
          OpenIDBackendProvider:
            provider: 'Dachcom\OpenID\Security\Authentication\Provider\OpenIDProvider'
            requestPatterns:
              controllerObjectName: 'Dachcom\OpenID\Controller\.*|TYPO3\Neos\Controller\.*|TYPO3\Neos\Service\.*|TYPO3\Media\Controller\.*'
